### PR TITLE
Simplify `queue` command by removing all extraneous workflow arguments

### PR DESCRIPTION
**Pull request by peppy**
## e4c9cb8 Tidy up initialisation and add warning when processing an old schema version

Just for my own sanity so I know what's going on when I run this manually in an incorrect state.

## bf3eef0 Remove `Wait` parameter

If this is needed, I think it should be defined in a `docker-compose` file similar to how it was done over [here](https://github.com/ppy/osu-queue-score-statistics/blob/master/docker-compose.yml).

## 0a05ff0 Remove `ForceVersion` parameter

Is not documented anywhere and I'd argue it adds more confusion than it's worth. I'd rather just run the `schema set` command instead.

- [ ] ppy/osu-web#9797

### CODE REVIEW

**Comment by peppy** [comment]
Parameters are apparently used by osu-web github actions, so will need consideration there before merging.

**Review by notbakaneko — CHANGES_REQUESTED** [review]
after testing a bit, `--force-version` can be removed; `--wait` is still needed for `osu-web`'s github action; the way web's docker-compose is currently set up for dev isn't practical for running the action atm.

**Comment by peppy** [comment]
Will probably leave this until we do the GHA docker compose switch then we can revisit. I think your feedback is on the right track though.

**Comment by peppy** [comment]
`osu-web` has switched across to using `docker-compose` for this, so I'll add this back to my ongoing todo list to get merged in.

**Comment by peppy** [comment]
@notbakaneko this should be good to go now.

**Comment by notbakaneko** [comment]
web still needs something to set the schema after the indexer is started, otherwise the index won't be aliased.

**Review by notbakaneko — DISMISSED** [review]
should be fine pending ppy/osu-web#9797

**Comment by peppy** [comment]
Wait, that dependency is a self reference....

**Comment by nanaya** [comment]
Can't we keep `--force-version` parameter? It causes additional complexity on osu-web side with the setting of the schema being strictly synchronous. osu-web doesn't even care about the active schema anymore apart of there being an aliased index (which is part of set schema iirc).

https://github.com/ppy/osu-web/pull/9797/files#diff-3074cf3b6f1779f081526e1f79cf72c1d23b8c2d2adc1fa2bb607749c3297ff7R93-R112

**Comment by peppy** [comment]
> Can't we keep `--force-version` parameter? It causes additional complexity on osu-web side with the setting of the schema being strictly synchronous. osu-web doesn't even care about the active schema anymore apart of there being an aliased index (which is part of set schema iirc).
> 
> https://github.com/ppy/osu-web/pull/9797/files#diff-3074cf3b6f1779f081526e1f79cf72c1d23b8c2d2adc1fa2bb607749c3297ff7R93-R112

@nanaya touching back on this, can you explain why the wait loop is required? Is the php test portion somehow running async to the `set-schema` command above?

**Comment by nanaya** [comment]
the set schema command must be run after the indexer starts otherwise the indexer won't create the correct index alias

**Comment by peppy** [comment]
Okay I've added back the ability to do this. I've made it `--set-current` instead as I think this reads better. Please update osu-web to match.

**Comment by nanaya** [comment]
I just remembered it's for the dev docker setup where the migration service (or whatever service to set the schema if the option is removed) needs to know if the score indexer is ready (and not just started) before setting the schema. I suppose adding a working health check for the indexer would also work.

**Comment by notbakaneko** [comment]
I looked into implementing a `healthcheck` for docker while reviewing the web side PR a while ago - it involved even more code to expose/signal that the indexer process was ready (one reason why `waitForElasticsearch()` polls for a specific status is because elasticsearch is http accessible before it's ready) and potentially even more packages installed since `healthcheck` runs on the container being checked itself.

It ended up that just telling the indexer what to is simpler.

**Pull request merged**
