### PR TITLE
Recalculate total score and accuracy during indexing

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-elastic-indexer/pull/125
- [x] https://github.com/ppy/osu/pull/20008
- [ ] Updated osu.Game nuget package with the above PR ^^.

I've tested that this indexes the scores with the re-written `total_score`/`accuracy` members, but I don't know how to test beyond that. Appreciate guidance/testing by others.

### CODE REVIEW

**Comment by notbakaneko** [comment]
Is total_score not set or something?

**Comment by nanaya** [comment]
legacy total score still need to be indexed (and added to schema).

Also I think there's another problem with having two different total scores as there can only be one sort option... I don't know how to fix it yet (short of having two different indexes).

**Comment by smoogipoo** [comment]
Yeah, I've yet to add `legacy_total_score` at all. I kinda had a brain fart that that's actually required for this PR to go through (right?).

**Comment by nanaya** [comment]
it's elasticsearch thing. The data need to be stored in one specific order so it can be accessed quickly. It's currently sorted by `total_score` and sorting by any other field will be quite a bit slower.

**Comment by smoogipoo** [comment]
Classic scoring matches standardised scoring, it's a constant (beatmap-wide) multiplier on top.

**Comment by nanaya** [comment]
At any rate, only one set of fields can be sort optimised per index. Currently it's `total_score, id`. If `legacy_total_score` is added then sorting by it will be slower. 

Hence the suggestion above to store total score for legacy (`data.legacy_total_score`) and lazer (calculated) in same field (`total_score`) with a flag indicating which is which. The side effect is there's no way to fetch both legacy and lazer scores in single query (sorted).

**Comment by nanaya** [comment]
The reason I mention classic scoring mode is if it makes sense displaying legacy and lazer score in same list, where total score for legacy is using `data.legacy_total_score` and for lazer is using `ComputeScore(ScoringMode.Classic)`, then storing by those will allow sorting in most cases (since the order shouldn't change between Classic and Standardised as far as I can tell and according to the comment in the function).

The only missing case would be showing legacy score in standardised unless it can just be the inverse of `ScoringMode.Classic` (something along the line `Math.Sqrt(legacy_total_score / ClassicScoreMultiplier) / Math.Max(1, totalBasicHitObjects)`).

**Comment by smoogipoo** [comment]
Yes, ordering scores by classic score or standardised score doesn't change ordering between those two scoring modes. But classic score can't be compared to legacy score since they're not necessarily even on the same magnitude scale. For example mania scores exceed 1M score in "classic" mode.

So the options would either be to display _everything_ in standardised/classic scoring mode with the new ordering, or display _just_ legacy scores with the legacy total score (and not display new scores). Eventually everything will be displayed with the standardised/classic scoring mode, so legacy scores are converted and is exactly what the code in this PR does.

The only reason for `legacy_total_score` to exist is to make sure we don't lose data, because we can't recover it.

So perhaps having two leaderboards, one which is "legacy" and displays _just_ legacy scores, and an "osu!lazer"/"next" leaderboard that displays everything. Is that not possible?/Is the `IsLegacy` flag enough for that?

**Comment by smoogipoo** [comment]
Also please provide input on how leaderboards should be displayed @peppy

**Comment by peppy** [comment]
I think you may be missing some important detail here.

Primarily, we are looking to migrate existing scores to the new table format. We are not changing score display.

To make this work short-term, the elastic schema needs a valid index that will allow displaying *only lazer score ordered by lazer total_score*, or *only stable score ordered by stable total_score*.

As mentioned by @nanaya, two different sort indices cannot exist, so the proposal is to have *one* `total_score` field in ES with `legacy_total_score` (if legacy score) or `total_score` (if lazer) alongside a new `bool` which denotes whether a score is legacy or not (also added to the index to allow the dual lookups).

**Comment by smoogipoo** [comment]
Alright, sounds fine.

**Comment by nanaya** [comment]
@notbakaneko please check if I'm missing something or if there's better way to handle this

**Comment by notbakaneko** [comment]
So, how many types of ordering are there going to be?
- classic/standard
- legacy?

`legacy_total_score` ordering may not be the same as `total_score` and some scores might not have a `legacy_total_score`, but it needs to be sortable on either if both are available, is that correct?

Which score is being calculated by `populateTotalScore`? Is anything going to update the DB with this value?

**Comment by notbakaneko** [comment]
It may also be worth considering enabling `_source` for some fields so that web can use those values directly; these were originally disabled because of the additional IO load from reading and writing those segments.

**Comment by peppy** [comment]
What is the `_id` currently consisting of that would cause clashes? I'm not sure I follow.

**Comment by nanaya** [comment]
id is `solo_scores` id which includes both legacy and lazer scores so there's no problem there.

**Comment by smoogipoo** [comment]
I think the problem is that there's two conflicting ideas. Going by peppy's idea:

> To make this work short-term, the elastic schema needs a valid index that will allow displaying
> 
>     * _only_ lazer scores ordered by lazer `total_score` (api return to lazer client)
> 
>     * _only_ stable score ordered by stable `total_score` aka `legacy_total_score` (`osu-web` and `web-10` displays)

Then the above are non-issues, correct? Because ID is unique to the scoring method of that ID - legacy or non-legacy.

**Comment by notbakaneko** [comment]
> we'll never display osu!lazer+osu!stable scores on the same leaderboard for now.

Whether they're displayed together or not isn't relevant - is a single `SoloScore` going to have more than one sort order? i.e. does this case exist?

id | total_score | legacy_total_score
-- |--|--
1 | 100 | 101 
2 | 99 | 100 
3 | 98 | 102

If it does then they should be stored as separate documents in the index

**Comment by nanaya** [comment]
> > we'll never display osu!lazer+osu!stable scores on the same leaderboard for now.
> 
> Whether they're displayed together or not isn't relevant - is a single `SoloScore` going to have more than one sort order? i.e. does this case exist?

The display is the sort. SoloScore (legacy) will only have `legacy_total_score` sort and SoloScore (lazer) will only have `total_score` (computed, now also stored) sort.

**Comment by notbakaneko** [comment]
> What is the `_id` currently consisting of that would cause clashes? I'm not sure I follow.

`_id` is the document's identifier in elasticsearch and has to be unique, it's currently set to use the score's `id` but they're not the same thing. If stable and lazer scores will have a different order when sorted, then the scores should be stored as separate documents, meaning the document's `_id` needs to be different from the score's `id`.

**Comment by nanaya** [comment]
> If stable and lazer scores will have a different order when sorted, then the scores should be stored as separate documents, meaning the document's `_id` needs to be different from the score's `id`.

They're already two different scores. Lazer scores come from lazer client (and only have lazer total score), stable scores come from stable client (and only have legacy total score).

**Comment by notbakaneko** [comment]
Then `['is_legacy', 'total_score', 'id']` should be fine

**Comment by smoogipoo** [comment]
Going to close this PR for now then, reimplementation will differ a bit.

**Pull request closed without merging**
