### PR TITLE
Add id to schema's sort option for tie breaker

### PR DESCRIPTION
**Pull request by nanaya**
Speeding up the most basic leaderboard query.

### CODE REVIEW

**Comment by peppy** [comment]
I guess the goal is to keep things simple and not require the post-retrieval sort step (as discussed last week)?

Does this add much overhead to the index size?

**Comment by nanaya** [comment]
I don't have direct comparison but with 1.03B data with this and convert attribute is 88.9GB. Compared to 1.05B data without either at 88GB.

**Comment by peppy** [comment]
Seems good 👍

**Review by peppy — APPROVED** [review]

**Review by notbakaneko — APPROVED** [review]
Shouldn't affect index size since the field is already there

**Pull request merged**
